### ISSUE TITLE
Закрывающая кавычка не превратилась в ёлочку

### ISSUE THREAD

**Issue by dunpeal** [emuravjev/mdash#24]
Здравствуйте!

Если этот текст пропустить через типограф (3.4), то кавычки после Мамы и Не все коту масленица не становятся елочками.
<pre>
<p><strong>Где ты могла меня видеть? </strong><br />
В самом добром кино &ldquo;Мамы&rdquo;, в&nbsp;молодежном триллере &ldquo;Закрытая школа&rdquo; на СТС. А еще на сцене театра им. Вл. Маяковского в спектакле &ldquo;Не все коту масленица&rdquo;.</p>
</p>

**Comment by dunpeal** [comment]
@vrnehot https://github.com/emuravjev/mdash/pull/31 решает проблему «Афиши+"

**Comment by vrnehot** [comment]
Еще один проблемный для кавычек символ - ó, ну и похоже все из этой серии.

К сожалению в регулярных выражениях не очень разбираюсь, есть ли способ указать любой буквеный символ чтобы не только "a-zа-яё0-9" а еще и такие символы как "ó","¥","あ","⿇" учитывались?

**Comment by Dr-Alex** [comment]
Все проблемы, обозначенные в теме, исправлены - @vrnehot, @greensk, @dunpeal. Тесты добавлены.
