### ISSUE TITLE
Привязка инициалов к фамилиям

### ISSUE THREAD

**Issue by vrnehot** [emuravjev/mdash#29]
Озвученное правило вызывает подобные эффекты:
`В 2000 году ему предложили снять несколько серий детективного сериала «Черная комната» для канала РЕН ТВ.`
Превращается в
`В 2000 году ему предложили снять несколько серий детективного сериала «Черная комната» для канала РЕН Т.В.`

**Comment by emuravjev** [comment]
Спасибо, проверим. Готовим новую версию.

**Comment by emuravjev** [comment]
А как в данном случае определить, что это не фамилия? Можно было бы добавить определение заглавных букв в слове РЕН, но это не решит проблему при написании Рен ТВ. В вашем случае предлагаю отключить это правило. Буду рад предложениям по исправлению.

**Comment by emuravjev** [comment]
По умолчанию правило выключено.
