### ISSUE TITLE
Ссылки и split_number

### ISSUE THREAD

**Issue by AlinaSob** [emuravjev/mdash#42]
Здравствуйте! 
Имеем: самописный сайт + redactor от Imperavi (http://imperavi.com/redactor/ ) + EMT. 
Типограф вызываю при сохранении статьи, на сервере (не через Ajax запрос). Поймала следующий баг: если в статье есть ссылки вроде http://www.bolshoyvopros.ru/questions/693440-kogda-otmechaetsja-den-synovej-kakie-pozdravlenija-s-dnjom-synovej.html (обратите внимание на цифры и дефис после них), то типограф падает с ошибкой: 
#8192

Non-static method EMT_Lib::split_number() should not be called statically, assuming $this from incompatible context
location
/хххх/хххх/htdocs/inc/EMT.php(1006) : eval'd code at line 1

**Comment by ssitdikov** [comment]
Можно убрать правило разбиения чисел на триады или заменить replacement на function => split_number

**Comment by Dr-Alex** [comment]
Падание исправил. Со ссылкой надо поработать - похожая проблема описана в #41
