### ISSUE TITLE
Как убрать ВСЕ неразрывные пробелы &nbsp;?

### ISSUE THREAD

**Issue by stripytiger** [emuravjev/mdash#48]
'Etc.unicode_convert' => 'on' убирает всё, кроме &nbsp
Подскажите пожалуйста как мнемонический символ &nbsp убрать в выдаче?

**Comment by Dr-Alex** [comment]
На данный момент это работает в версии 3.5. К примеру с помощью АПИ запускаем с опцией OFF:
http://mdash.ru/api.v1.php?text=Text%20TS&Text.paragraphs=off&Etc.unicode_convert=off
получаем
 `{"result":"Text&nbsp;TS"}`
Запускаем с опцией ON
http://mdash.ru/api.v1.php?text=Text%20TS&Text.paragraphs=off&Etc.unicode_convert=on
получаем
`{"result":"Text\u00a0TS"}`
