### ISSUE TITLE
Ломается на обработке безопасных тегов

### ISSUE THREAD

**Issue by avlysenko** [emuravjev/mdash#54]
Написано что в 2015 году уже фиксили проблему, но простой пример осыпается. :-(

```
$t = new \Emuravjev\Mdash\Typograph();  
$t->add_safe_tag('code');
$t->set_text("<pre><code>text</code></pre>");
echo $t->apply();
```

Тикет из прошлого: https://github.com/emuravjev/mdash/issues/16

**Comment by Dr-Alex** [comment]
Сейчас проверил - воспроизвести не получается. Я даже делал регтест по этой проблеме и он не нарушается: "Тест E12 (141/164): Баг двойного декодирования safe tags"
Предположу, что 
`$t = new \Emuravjev\Mdash\Typograph();`
используется какой-то форк старой версии, попробуйте версию 3.5.
